DOCKERFILE CODE

FROM --platform=linux/amd64 python:3.8-slim
RUN pip install --upgrade pip
RUN pip install boto3 sagemaker pandas scikit-learn joblib imbalanced-learn

ENV PATH="/opt/ml/code:${PATH}"

COPY train.py /opt/ml/code/train.py

RUN chmod +x /opt/ml/code/train.py

ENTRYPOINT ["python", "/opt/ml/code/train.py"]
